### ISSUE TITLE
Unparseable number exceptions

### ISSUE THREAD

**Issue by aosagie** [snowflakedb/spark-snowflake#107] opened 2019-03-19 06:26 UTC
Hi,
Numerous people at my organization have been getting the following exception from their jobs:
<img width="1248" alt="Screen Shot 2018-11-20 at 9 25 11 AM" src="https://user-images.githubusercontent.com/1888108/54583682-51cc5a80-49eb-11e9-925e-a7f39acf3c8a.png">

This appears to be due to fields that are null, but deemed non-nullable, being converted into empty strings: https://github.com/snowflakedb/spark-snowflake/blob/30f50c8d6b4094bf21597035390f518f626af7be/src/main/scala/net/snowflake/spark/snowflake/Conversions.scala#L148

Which subsequently causes the exception to be thrown because an empty string can't be converted into a number: https://github.com/snowflakedb/spark-snowflake/blob/30f50c8d6b4094bf21597035390f518f626af7be/src/main/scala/net/snowflake/spark/snowflake/Conversions.scala#L159

The weird thing is that the column metadata shows that the field is non-nullable, while "show column in table" and "desc table" both show the field as nullable.

Results in Spark:

<img width="797" alt="Screen Shot 2019-03-17 at 2 17 11 AM" src="https://user-images.githubusercontent.com/1888108/54584289-4da13c80-49ed-11e9-9ad3-e68aa04d49fe.png">

Results in Snowflake:

<img width="674" alt="Screen Shot 2019-03-17 at 2 13 08 AM" src="https://user-images.githubusercontent.com/1888108/54584308-5a259500-49ed-11e9-83dc-2c099ccf264f.png">

The results in Spark appear to be incorrect. I assume it's using the metadata from this query?: https://github.com/snowflakedb/spark-snowflake/blob/32e6f625230f72ca4fe90c9fa4d8d0ce689969ae/src/main/scala/net/snowflake/spark/snowflake/SnowflakeJDBCWrapper.scala#L470-L473

I tried to write a PR to replace the apparent bad query with one of the good ones, but that would only allow us to get the columns of tables and not queries.

Running these queries from python give the same problems, so perhaps the REST endpoint is returning unexpected results.

We currently hack around this by setting all columns to nullable, but any help you can provide would be greatly appreciated.

**Comment by binglihub** [comment] 2019-06-18 21:07
I can't reproduce your issue. Could you provide an example table schema, and queries getting this issue? Thanks.

**Comment by swekaj** [comment] 2019-08-07 18:07
I have also encountered this issue.  Here are example schema and queries I used to reproduce it:
```
-- In Snowflake, create these tables with this data
create schema TEST;
create or replace table TEST.LEFT_TABLE (id decimal not null);
create table TEST.RIGHT_TABLE (id decimal not null, flag varchar not null);
insert into TEST.LEFT_TABLE values (1), (2), (3), (4), (5);
insert into TEST.RIGHT_TABLE values (1, 'a'), (2, 'b'), (4, 'd');
```

```
# In pyspark
spark.read.format('snowflake').options(**sfOptions).option('dbtable', 'TEST.LEFT_TABLE').load().createOrReplaceTempView('LEFT_TABLE')
spark.read.format('snowflake').options(**sfOptions).option('dbtable', 'TEST.RIGHT_TABLE').load().createOrReplaceTempView('RIGHT_TABLE')
spark.sql('select l.id, r.flag, length(r.flag) from LEFT_TABLE l left outer join RIGHT_TABLE r on l.id = r.id').show()
```

For me, my workaround was disable the `autopushdown` connection option.  That prevents the join from getting pushed down to Snowflake, thus preventing `null` values in a non-nullable field from being saved to and converted from CSV.

**Comment by Mingli-Rui** [comment] 2020-01-24 20:14
This issue is fixed in https://github.com/snowflakedb/spark-snowflake/pull/176

**Closed by Mingli-Rui** 2020-01-24 20:14 UTC
